# Generated by Django 5.1.7 on 2025-05-27 13:03

from django.db import migrations

from data.etl.teleicare_history.extractor import convert_str_date, get_oldest_and_latest

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0149_alter_declaration_teleicare_id_and_more'),
    ]

    def set_default(apps, schema_editor):
        IcaDeclaration = apps.get_model("data", "IcaDeclaration")
        Declaration = apps.get_model("data", "Declaration")
        for teleicare_withdrawn_declaration in Declaration.objects.filter(status="WITHDRAWN").exclude(siccrf_id=None):
            teleicare_snapshot = teleicare_withdrawn_declaration.snapshots.latest("creation_date")
            all_ica_declarations = IcaDeclaration.objects.filter(
                    cplalim_id=teleicare_withdrawn_declaration.siccrf_id
                ).exclude(icaversiondeclaration__isnull=True)
            _, latest_ica_declaration = get_oldest_and_latest(all_ica_declarations)
            teleicare_snapshot.effective_withdrawal_date = (
                    convert_str_date(latest_ica_declaration.dcl_date_fin_commercialisation, aware=True)
                    if latest_ica_declaration.dcl_date_fin_commercialisation
                    else None
                )
            teleicare_snapshot.action = 'WITHDRAWN'
            teleicare_snapshot.save()
            if teleicare_withdrawn_declaration.snapshots.count() == 1:
                logger.info(f'{teleicare_withdrawn_declaration.id} a plusieurs snapshot')

    def reverse_set_default(apps, schema_editor):
        pass

    operations = [
        # Cette migration a été effectuée manuellemement pour eviter l'erreur liée au tables unmanaged : 
        # django.core.exceptions.FieldError: Cannot resolve keyword 'cplalim_id' into field.
        # migrations.RunPython(set_default, reverse_set_default),

    ]
